### ISSUE TITLE
decide on using svg files

### ISSUE THREAD

**Issue by tsotneforester** [feraldruid1/bitcamp.etherium-card#1]
https://stackoverflow.com/questions/23210126/inline-svg-vs-svg-file-performance

ჩამოყალიბდი, svg ფაიები img ტაგით შემოიტანო თუ svg კოდით, გაეცანი სტატიას და დაახლოებით მიხვდები პლიუსებს და მინუსებს პრივე მეთოდის

**Comment by feraldruid1** [comment]
წავიკითხავ ეხლა პროსტა პირველად რო ვისწავლე ესე ქნეს მაგის მერე დავიკიდე
არც დავფიქრებულვარ ესეათქო ვფიქრობდი

ორშ, 2 იან. 2023, 12:15-ში Tsotne Meladze ***@***.***> დაწერა:
